import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Link from "next/link";
import Footer from "./components/footer"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="drawer">
          <input id="my-drawer" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content">
            <Navbar/>
            {children}
            <Footer/>
          </div>
          <div className="drawer-side">
            <label
              htmlFor="my-drawer"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            
            <ul className="menu bg-base-200 text-base-content gap-3 min-h-full w-80 p-4">
            <div className="text-2xl font-bold">Dashboard</div>
              {/* Sidebar content */}
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/browse">Browse</Link>
              </li>
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
